//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid BFAttendee = new Guid("cc407c1d-fa3f-47ad-b7b4-c921dd0c40cd");
		public static readonly Guid CustomerAI = new Guid("89bc2e50-c168-49d7-96b9-c887ffba2e32");

    }
}
